//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OneClickToProd.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class UILogging {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UILogging() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OneClickToProd.Resources.UILogging", typeof(UILogging).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed, hit a key to close this console..
        /// </summary>
        internal static string Completed {
            get {
                return ResourceManager.GetString("Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect to SSH.
        /// </summary>
        internal static string ConnectSSH {
            get {
                return ResourceManager.GetString("ConnectSSH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creation du tag SVN.
        /// </summary>
        internal static string CreateSvnTag {
            get {
                return ResourceManager.GetString("CreateSvnTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnect of SSH.
        /// </summary>
        internal static string DisconnectSSH {
            get {
                return ResourceManager.GetString("DisconnectSSH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        internal static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found version {0}.
        /// </summary>
        internal static string FoundSVNVersion {
            get {
                return ResourceManager.GetString("FoundSVNVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get the svn version.
        /// </summary>
        internal static string GetSvnVersion {
            get {
                return ResourceManager.GetString("GetSvnVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ....
        /// </summary>
        internal static string Spacer {
            get {
                return ResourceManager.GetString("Spacer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update SQL version.
        /// </summary>
        internal static string UpdateSQL {
            get {
                return ResourceManager.GetString("UpdateSQL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update SVN version.
        /// </summary>
        internal static string UpdateSVN {
            get {
                return ResourceManager.GetString("UpdateSVN", resourceCulture);
            }
        }
    }
}
